version: 2

sources:
  - name: gz_raw_data
    description: greenweez raw data source
    tables:
    - name: raw_gz_sales
      description: sales of greenweez / we have one row per products_id found in each orders_id.
      columns:
        - name: date_date
          description: date of the order
  
      tests:
        - unique:
            column_name: "(orders_id || '-' ||pdt_id)"
       

    - name: raw_gz_product
      columns:
        - name: products_id
          tests:
            - unique
            - not_null                
    - name: raw_gz_ship
      columns:
        - name: orders_id
          tests: 
            - unique
            - not_null

                
  